import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from "./components/Sidebar";
import Menu from './components/Menu';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Menu props="block md:hidden"/><div className="lg:flex"><Sidebar/>{children}</div></body>
    </html>
  )
}
